---
- name: Install pip3
  apt:
    name: python3-pip
    state: present
  become: true

- name: Install PyMySQL
  pip:
    name: PyMySQL
- name: update apt package
  ansible.builtin.shell: sudo apt-get update -y
  become: true
- name: Install Mysql server
  ansible.builtin.apt:
    name: mysql-server
    state: present
  become: true
- name: Ensure mysql started
  ansible.builtin.service:
    name: mysql
    state: started
  become: true
- name: Set root user password`
  community.mysql.mysql_user:
    name: ''
    login_unix_socket: /run/mysqld/mysqld.sock
    host: localhost
    login_user: root
    login_password: ""
    state: absent